### ISSUE TITLE
https://pub.flutter-io.cn 部分包下载失败

### ISSUE THREAD

**Issue by ensean** [cfug/flutter.cn#611]
Hi, 一直将pub-flutter-io.cn作为镜像使用，最近发现部分包下载失败
```
https://pub.flutter-io.cn/packages/sqfentity_gen/versions/1.2.3%2B18.tar.gz
```
访问上述地址时，浏览器返回报错如下
```
{"error":"get from image source failed: E424"}
```
看着像是七牛云存储的报错？

**Comment by chenglu** [comment]
谢谢提出，问题已经修复。原因是走了一部分阿里云 OSS 的回源结果造成了 URL 中包含了特殊 URL 不兼容的问题，造成的不便非常抱歉，如果有任何问题请随时再提出。

**Comment by ensean** [comment]
> 谢谢提出，问题已经修复。原因是走了一部分阿里云 OSS 的回源结果造成了 URL 中包含了特殊 URL 不兼容的问题，造成的不便非常抱歉，如果有任何问题请随时再提出。

感谢秒回👍

**Comment by ensean** [comment]
又出现了……
```
https://pub.flutter-io.cn/packages/connectivity_platform_interface/versions/2.0.0.tar.gz
```

```
{"error":"get from image source failed: E403"}
```

**Comment by chenglu** [comment]
我检查了一下，上游的数据似乎也出现了问题：
https://storage.googleapis.com/pub-packages/packages/connectivity_platform_interface-2.0.0.tar.gz
我再看一下，有消息回复你。

**Comment by chenglu** [comment]
请先暂时将镜像切到清华源测试一下，他们是通过数据拷贝同步、在前端搭建 API 请求的方式完成的，他们的源可以正常下载，没有这个问题。
```
export FLUTTER_STORAGE_BASE_URL: https://mirrors.tuna.tsinghua.edu.cn/flutter
export PUB_HOSTED_URL: https://mirrors.tuna.tsinghua.edu.cn/dart-pub
```

**Comment by ensean** [comment]
> 请先暂时将镜像切到清华源测试一下，他们是通过数据拷贝同步、在前端搭建 API 请求的方式完成的，他们的源可以正常下载，没有这个问题。
> 
> ```
> export FLUTTER_STORAGE_BASE_URL=https://mirrors.tuna.tsinghua.edu.cn/flutter
> export PUB_HOSTED_URL=https://mirrors.tuna.tsinghua.edu.cn/dart-pub
> ```

好的

**Comment by chenglu** [comment]
@ensean 我看了一下 package 的 CDN 记录，这个 package 确实在 2/20 之后有过一次版本刷新 (2020-02-27 09:09:08)，我个人判断目前请求的 2.0.0 版本（如果有）应该是误发布。
目前 [官网更新最新版本](https://pub.flutter-io.cn/packages/connectivity_platform_interface/versions) 是 2/20 更新的 1.0.3，为了确保项目的稳定运行，建议退回使用 1.0.3 版本。

cc/ @xster @liyuqian let me know if you know more insights about this package's 2.0.0 version since it's developed by the Flutter team, thanks!

**Comment by liyuqian** [comment]
I believe the 2.0.0 version of package connectivity_platform_interface is introduced by @ditman's commit https://github.com/flutter/plugins/commit/4411247270069e8b4d4969652b6c2d1d9b694d82 , which is later reverted. Such version increase and decrease is causing some problems in pub.dev's China mirror. I wonder if Dart pub supports decreasing the version number (e.g., 1.0.3 -> 2.0.0 -> 1.0.3)? CC @amirh @tvolkert

**Comment by ditman** [comment]
Version 2.0.0 of the package was **deleted** from pub.dev because I published it by mistake.

Is pub.flutter-io.cn broken?

**Comment by liyuqian** [comment]
AFAIK, pub.flutter-io.cn is not broken, but some package that depends on
connectivity_platform_interface is now having trouble getting downloaded
from that mirror.

**Comment by ditman** [comment]
Very weird, no packages should have ever depended in `connectivity_platform_interface 2.0.0`

**Comment by chenglu** [comment]
Let me ask @ensean: I'd like to know your pubspec file(pubspec.lock or pubspec.yaml) to see how your project use `connectivity_platform_interface 2.0.0`, since there're no packages depended the `connectivity_platform_interface 2.0.0`, are you directly define the 2.0.0 version in your pubspec file?

HI YinXiang: 我们想知道你的项目里是如何调用 2.0.0 版本的 `connectivity_platform_interface`，以帮助我们更好的排查这个问题，是否可以帖一下或者部分展示一下 pubspec.lock 或者 pubspec.yaml 的代码，因为看起来没有任何 package 是依赖 2.0.0 版本的，你是否是直接在 pubspec 文件里定义了拉取 2.0.0 版本？

Thank you for your time, @ditman, @liyuqian !

**Comment by ensean** [comment]
@chenglu To be honest, we currently use flutter-cn.io as upstream for the mirror inside our company. Maybe this is caused by package index cache?

**Comment by chenglu** [comment]
@ensean: 
Great, thanks for let me know, for now, please define and use the 1.0.3 version of the package `connectivity_platform_interface` since this version will be more realiable.
I also saw your [issue](https://github.com/huiyiqun/pub-mirror/issues/6) on the pub-mirror project, did you use that solution for building your internal pub.dev site?

@ditman: there's no issue from the Flutter team side, thanks again for your time!

@liyuqian:
这可能会是另外一个话题，关于如何“商业化”的在企业中使用 Flutter，包括不仅限于其 Flutter 工具、镜像、内部的 package 构建&协作&获取 等。
我个人的建议是由 Flutter 团队来做一些类似的、基础的最佳实践以免国内的公司自己摸索而导致效率问题。所有的工具都是开源的也并不代表大家都能很好把这些东西应用到商业化环境里去。
亦或可以号召社区共享、协作这样的一个方案，这会极大程度帮助在国内推广 Flutter。
（个人建议，供参考）

**Comment by ensean** [comment]
@chenglu Yep, I am using pub-mirror as the tool to sync with fultter-io.cn

**Comment by chenglu** [comment]
@ensean: OK great, thanks for letting me know!
I have already mentioned this situation that should delete the file and update the API returns when the package's version delete.

**Comment by liyuqian** [comment]
Thanks @chenglu for the suggestion! Loop in @zoeyfan
