### ISSUE TITLE
'Adding assets and images' page issue

### ISSUE THREAD

**Issue by KenChoi1992** [cfug/flutter.cn#797]
Page URL: https://flutter.cn/docs/development/ui/assets-and-images.html
Page source: https://github.com/cfug/flutter.cn/tree/master/src/docs/development/ui/assets-and-images.md

Found a typo? You can fix it yourself by going to the page source and clicking the pencil icon. Or finish creating this issue.

Description of issue:
You're not describe how to load assets files like JSON from packages, which waste my damn fucking whole afternoon to just checking my damn pubspec.yaml again and again!
Please add how to load assets files to the damn document, so that prevent wasting others' life !
```
var content = await rootBundle.loadString('packages/[package name]/assets/[JSON file name]);
```

**Comment by AlexV525** [comment]
A chinese people, posting content in non-chinese, insulting chinese people, and show his disrespect? You're really a good person, I personally felt shame about JiGuang company hired someone like you.

Closing with dulp with https://github.com/flutter/website/issues/5209 .

Locking and banning because of your disrespect.
